
[functions.send_unresponded_invite_reminders]
enabled = true
verify_jwt = true
import_map = "./functions/send_unresponded_invite_reminders/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/send_unresponded_invite_reminders/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/send_unresponded_invite_reminders/*.html" ]

[functions.send_24hr_event_reminders]
enabled = true
verify_jwt = true
import_map = "./functions/send_24hr_event_reminders/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/send_24hr_event_reminders/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/send_24hr_event_reminders/*.html" ]

[functions.send_7day_event_reminders]
enabled = true
verify_jwt = true
import_map = "./functions/send_7day_event_reminders/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/send_7day_event_reminders/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/send_7day_event_reminders/*.html" ]
